### ISSUE TITLE
Having trouble getting this working in a este project (https://github.com/este/este)

### ISSUE THREAD

**Issue by jdart** [glortho/react-keydown#12]
I'm new to react so I could be doing something wrong. I'm trying to use the method decorator pattern which seems pretty straight forward, but my method is never firing. I stepped through some of your project code and from what I can tell in method_decorator.js (dist version) line 35, "var componentDidMount = target.componentDidMount;" is receiving undefined. 

I realize this isn't much info, what can I do to debug this issue?

**Comment by glortho** [comment]
Sorry to hear of the troubles. If you post your component code I'll take a look, though it will definitely yield undesirable results when run server-side since it blindly relies on a global document object and the DOM API.

**Comment by glortho** [comment]
I also need to update the documentation to show that version 1.4+ is meant to be used with React 0.14+ and 1.3 with React 0.13-.

**Comment by jdart** [comment]
I'll share the exact code tonight, but it's based on a component like this: https://github.com/este/este/blob/master/src/client/home/Page.react.js

just with the added "@keydown ( keys.RIGHT ) doStuff() { console.log('firing') }"

Any chance that using react-pure-render as the base class is causing a problem?

**Comment by jdart** [comment]
fwiw i ended up using "document.addEventListener("keydown", ...);" in componentDidMount and that worked, even with server side rendering.

**Comment by glortho** [comment]
Okay thanks for the info @jdart . I haven't looked closely yet but it's possible that using es7 class properties breaks things, or that the extra class extension you mentioned is involved. If you post your code (and ideally a codepen, but I know that may be too complex) I'll take a closer look.

**Comment by glortho** [comment]
Actually @jdart can you try going the class decorator route and see if that works? That will help narrow things down:

```
@keydown( keys.RIGHT )
class MyClass extends Component {
  componentWillReceiveProps( { keydown } ) {
    if ( keydown.event ) console.log( keydown.event.which );
  }
}
```

**Comment by glortho** [comment]
For anyone else who lands here note that decorator support is currently broken in Babel 6.x - https://github.com/babel/babel/issues/2711
