### ISSUE TITLE
babel 6 compatibility

### ISSUE THREAD

**Issue by ali** [glortho/react-keydown#13]
The readme mentions that decorators are currently broken in Babel 6. Has anyone recently tried this library with the latest version of Babel?

> NOTE: If react-keydown isn't working for you, be sure to check that you're not using Babel 6.x, as [decorators are currently broken in Babel 6](https://github.com/babel/babel/issues/2645).

The link in that note (https://github.com/babel/babel/issues/2645) is broken, and the [Babel 6.0 release blog post](http://babeljs.io/blog/2015/10/29/6.0.0/) mentions decorator support:

> There are a couple of updated TC39 proposals that have come out. Babel 6 updates to the latest revisions of decorators, class properties, and others.

It seems like all you need to do is enable the [stage 1 preset plugin](http://babeljs.io/docs/plugins/preset-stage-1/) to get decorator support.

**Comment by glortho** [comment]
Thanks for this prompting @ali . The issue moved out of GitHub to phabricator: https://phabricator.babeljs.io/T2645

I see there that @loganfsmyth has patched in the old decorator proposal as a plugin -- https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy -- so if the new proposal implementation in Babel 6 doesn't work predictably the plugin should help.

The dist of react-keydown should work in any event, but I'll do some testing on my side to see what else I can find out.
