### ISSUE TITLE
TypeError: (0 , _store.getBinding) is not a function

### ISSUE THREAD

**Issue by babsonmatt** [glortho/react-keydown#14]
@keydown on a method appears to work but @keydown('enter') on a method and @keydown/@keydown('enter') on a class throws `TypeError: (0 , _store.getBinding) is not a function` 

Any ideas? Thanks!

**Comment by glortho** [comment]
Sorry for the delay @babsonmatt. Are you using Babel 6+?

**Comment by glortho** [comment]
I believe https://github.com/glortho/react-keydown/commit/39c2c39e8d97b393600cb8d5c40cb212f8c00bb2 addresses that issue @babsonmatt but reopen if you still have problems.
