### ISSUE TITLE
Wrong module name on gh-pages website

### ISSUE THREAD

**Issue by tofuness** [glortho/react-keydown#15]
Currently says `import {...} from 'keydown'`. Should be `import {...} from 'react-keydown'`

http://glortho.github.io/react-keydown/example/index.html

**Comment by glortho** [comment]
Thank you for the correction @desuvader. I'll push the change tomorrow. 

```
_____________________________
```

**Comment by glortho** [comment]
Fixed in ea8168a0c93ca27e76e1725181c076cdadf09675
