### ISSUE TITLE
Capture window keydown events

### ISSUE THREAD

**Issue by joshwcomeau** [glortho/react-keydown#17]
I'm wondering if it's possible to capture events that aren't specifically sent to the component, but to still trigger a component's method.

My usecase is I have a grid in the center of the page, and I'm moving a little box around within it using the arrow keys. This works perfectly when the grid has "focus" by clicking on it, but I'd like for it to be able to capture keydown events on the window/document overall.

Not a huge problem if it's not possible, just thought I'd check if it is. This is an awesome library, super well-crafted =)

**Comment by glortho** [comment]
@joshwcomeau My recommended way to do this is to decorate an ancestor class (it could be your root class if you really want it to be app-wide) with `@keydown( myKeys )` and then decorate your method inside the descendent class with `@keydownScoped( myKeys )` - or just inspect the `keydown.event` prop in the `componentWillReceiveProps` lifecycle method of that descendent class. Let me know if that still doesn't seem to get you what you need.

**Comment by joshwcomeau** [comment]
Thanks so much for the quick reply! 

I should have read the docs more carefully, that sounds like it'll work very well.

**Comment by glortho** [comment]
No problem. I should put a tl;dr in the docs for this since it's a pretty common need and it's buried pretty deep in there.
