### ISSUE TITLE
invalid version range according to semver

### ISSUE THREAD

**Issue by mkampik** [glortho/react-keydown#21]
I am having trouble installing `react-keydown` via [jspm](https://github.com/jspm/jspm-cli), which converts version ranges down to  `^` and `~` operators in an attempt to naturally enforce semver.

It seems that the the specified `react-dom` range of `>=^0.14.0` is not a valid range according to https://github.com/npm/node-semver and thus fails to install.

Could you please consider changing the `react-dom` version range to `^0.14.0` to ensure compatibility with jspm?

Thanks in advance,

Max

**Comment by glortho** [comment]
Thanks @mkampik - fixed in 1.4.9.

**Comment by mkampik** [comment]
Great, that did the trick. Thanks for the quick fix and nice work on react-keydown!
