### ISSUE TITLE
Programatically switching focus

### ISSUE THREAD

**Issue by mzgajner** [glortho/react-keydown#28]
The plugin generally works well for me as long as I use clicking to switch focus between components. But I'm making an app that is keyboard-only and would like to manually choose which component is currently active. For example:
- I have a sidebar with menu items which I navigate with keys.
- I press enter on an item, which renders a subpage on the right;
- at this point I would like to switch focus to this subpage (without clicking on it, of course) so that it receives key events instead of the sidebar.

I have tried calling `.focus()` on the primary element of the component I'd like to focus, but it doesn't seem to do anything. Is there a way to do this?

**Comment by glortho** [comment]
It should be the case that the most recently mounted component with keybindings receives keystrokes, until you focus somewhere outside the scope of that component. Is your subpage already mounted before you press enter on the item, and the showing of the subpage is just toggling visibility or something?

**Comment by mzgajner** [comment]
Yup, the description was slightly simplified, the "subpage" is an already mounted component.

**Comment by glortho** [comment]
Okay that makes sense. I haven't verified this but you should be able to call react-keydown's `onMount` handler programmatically, passing in the component instance. So it'd be something like this:

```
import { onMount } from 'react-keydown/dist/event_handlers';

class MyComponentWithKeybindings extends React.Component {
  componentWillReceiveProps( nextProps ) {
    if ( nextProps.isActive ) {
      onMount( this );
    }
  }
  ...
}
```

**Comment by mzgajner** [comment]
Works like a charm! Thanks for a very prompt response ❤️

**Comment by basharov** [comment]
Advice by @glortho works just as expected in a TypeScript project, thanks!
