### ISSUE TITLE
Support React v15

### ISSUE THREAD

**Issue by illuminardy** [glortho/react-keydown#31]
Is there any plan to update the module to accept React v15 as a dependency. I did this locally, by updating package.json, but curious if it was something you were planning on doing. 

Thanks.

**Comment by glortho** [comment]
@illuminardy I would expect it to work with v15 since it has react at `>= 0.14.0` (and is in fact working for us with 15.3.1). this isn't the case for you?

**Comment by illuminardy** [comment]
Thanks for the response. I will re-verify and let you know.

**Comment by illuminardy** [comment]
Looks like it works now. I'll close the issue. Thanks for the help
