### ISSUE TITLE
Doesn't work. Pure shit.

### ISSUE THREAD

**Issue by cyllu2** [glortho/react-keydown#34]
1) Fails with no error message.
2) Extremely bad documentation.
3) Doesn't do anything that a simple onKeyDown doesn't do.

**Comment by glortho** [comment]
Sorry to hear of your troubles @cyllu2 . If you're interested in making it work, feel free to post sample code of how you're trying to use it and I'll take a look. If you've moved on to other solutions, carry on!

**Comment by machineghost** [comment]
Wow, what a polite response to a truly juvenile submission. @cyllu2 should be ashamed of themselves.

**Comment by glortho** [comment]
Ha thanks for the note, Jeremy. I've had my fair share of disgruntlement trying to get libs to work and generally want to help people reduce theirs. My guess is that this user isn't already well acquainted with decorators, and the Babel/tc39 issues around the proposal. A flaw in my documentation is that it more or less assumes you're already familiar with all of that. So point #2 above, if nothing else, could benefit from some attention. 



		_____________________________
