### ISSUE TITLE
Help With Enzyme-Based Testing

### ISSUE THREAD

**Issue by machineghost** [glortho/react-keydown#35]
`react-keydown` has worked great for me in the browser, but when I try to use Enzyme to test it I can't figure out how to simulate a keydown event that `react-keydown` will actually respond to.

If I have a component ...

    class SomeComponent extends React.Component {
        @keydown('ctrl+a')
        handler() {
            throw new Error(`Proof that we hit this line`);
        }
    }

and then I try to test it with Enzyme:

    const A_KEY = 65;
    const component = new SomeComponent();
    component.simulate('keyDown', {ctrlKey: true, keyCode: A_KEY})
    // an error should have been thrown here

no error ever gets thrown, indicating that the handler never got hit.

I tried looking through the source but wasn't able to figure out where exactly `react-keydown` looks at the event and decides which handler to forward to, so any help either:

A) pointing me toward that place in the code

B) (ideally) providing an example of how to use Enzyme to test `react-keydown`

would be greatly appreciated.

**EDIT**
Two minor follow up issues (both related to testing `react-keydown`-decorated methods directly instead of via `simulate`)

1. If you use Node.js + JSDom to run your tests things will break because

     ReferenceError: KeyboardEvent is not defined

That's easy enough to fix (`global.KeyboardEvent = window.KeyboardEvent`), but if `react-keydown` could just use `window.KeyboardEvent` it would save users from a potential pain point.

2. Methods decorated with `@keydown` lose their return values.  Obviously this doesn't matter normally, because event handlers don't normally return things, but it can be handy to have handlers return things for tests (eg. if the handler generates a promise, it can be handy for the test to get that promise back from the handler).

**Comment by glortho** [comment]
Ok thanks for this additional info @machineghost. I definitely need to resolve these oversights. Give me a day or two and I should have fixes.

**Comment by machineghost** [comment]
Thanks!

**Comment by glortho** [comment]
Okay @machineghost I believe I've addressed your issues 1 and 2 above in version 1.6.5. Try it out and let me know.

As for testing, react-keydown actually just does one binding on `document` for the keydown event and one for click events. See here: https://github.com/glortho/react-keydown/blob/master/src/lib/listeners.js

So you should be able to test by simulating a keydown event on `document` after your keydown-decorated component has mounted. Let me know if that doesn't work for you!

**Comment by machineghost** [comment]
> I believe I've addressed your issues 1 and 2 above in version 1.6.5. Try it out and let me know.

I did and it works great, thank you so much!

> As for testing ...

Right now the tests that prompted this ticket are "disassembled on the shop floor" (so to speak), and I've had to switch gears to something else.  However, as soon as I can get back to those tests I'll try simulating the key events on the document.

**Comment by glortho** [comment]
Sounds good @machineghost . Keep me apprised.
