### ISSUE TITLE
How to differentiate between enter and shift+enter?

### ISSUE THREAD

**Issue by iamthesiz** [glortho/react-keydown#37]
How do you handle shift+enter here?
```
@keydown('enter', 'shift+enter')
handleKeyDown({ keyCode }) {
  if (keyCode == SHIFT_ENTER) {
    // add a line break
  } else {
    // submit
  }
}
```

**Comment by glortho** [comment]
@alex-cory the whole [KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) is passed in as the arg so you should be able to check the value of `shiftKey`, something like:
```
handleKeyDown({ keyCode, shiftKey }) {
  if (shiftKey) ...
}
```

**Comment by iamthesiz** [comment]
glorious
