### ISSUE TITLE
Implementing a slack style enter entry

### ISSUE THREAD

**Issue by MattHartz** [glortho/react-keydown#38]
Hi, I'm trying to set up a textfield to, on enter, submit.  But to support adding newlines, add a keybinding for ctrl + enter.  Capturing ctrl+enter is simple using
` 
@keydown('ctrl+enter', 'enter')
  onKeyDown({ keyCode, ctrlKey }) {

  }

  render() {
    return (
      <TextField
        textareaStyle={styles.container}
        hintText="Send Announcements"
        fullWidth={true}
        multiLine={true}
        rowsMax={5}
      />
    );
  }
`
But, capturing just the simple 'enter' press, does not work.  Instead it gets handled, I assume by the Textfield itself. What is the best way to approach this?

**Comment by glortho** [comment]
@matthartz try calling that keydown-decorated method from onKeyDown in your text field. For example:
```
<input onKeyDown={ this.onKeyDown } />
```

**Comment by MattHartz** [comment]
Hi @glortho ,
My issue with this now calls onKeyDown twice if it matches the key combination.  For example pressing enter.

I tried that last night before submitting this post :)
