### ISSUE TITLE
Not woking for question mark

### ISSUE THREAD

**Issue by ashokkumarsand** [glortho/react-keydown#40]
when i press ?, the keydown is not working

**Comment by glortho** [comment]
@ashokkumarsand it's probably expecting `shift+/` (or whatever your key combination is for creating a question mark). we should set up aliases for key combinations like this so that `?` gets translated to `shift+/` and vice versa. i would certainly welcome a pr!

**Comment by ashokkumarsand** [comment]
@glortho Yeah this solution work. I map some symbols directly with key like m-> ?.
