### ISSUE TITLE
Usage with Stateless Functional Components?

### ISSUE THREAD

**Issue by vsc-github** [glortho/react-keydown#41]
Is there any way to use react-keydown with a stateless component? 

I know ES7 decorators are only supported with classes and not functions. Is there any workaround to this? Or do I have to switch to some other library? I really like react-keydown and would want to stick to it.

**Comment by glortho** [comment]
Sorry @vsc-github I just saw this message. You should be able to use `keydown` as a higher-order component, like this:
```
export default keydown( 'ctrl+a', 'ctrl+b')(
  function MyComponent( props ) {
    // check props.keydown.event
  }
)
```
