### ISSUE TITLE
[Question] Is there a way to bubble a captured event?

### ISSUE THREAD

**Issue by jorgerobles** [glortho/react-keydown#45]
I've got a situation I have first check some conditions, and if not met, let the event go upstream. Is that possible?

**Comment by glortho** [comment]
@jorgerobles events are caught off of `document` so unless you `stopPropagation()` somewhere they should bubble. Is that not happening for you?

**Comment by jorgerobles** [comment]
I was fiddling with some system keys, maybe that were interferences. I will check again, thanks!

**Comment by glortho** [comment]
okay, let me know and i'll re-open if need be.
