### ISSUE TITLE
add `es` build to allow tree shaking

### ISSUE THREAD

**Issue by wmertens** [glortho/react-keydown#47]
https://webpack.js.org/guides/tree-shaking/

For example, if you only use method decorators, it won't include the class decorator code (as long as you use ES6 export syntax and none of the modules are running functions that might have side-effects).

Here's how redux-form does it: https://github.com/erikras/redux-form/blob/master/package.json#L15

react-keydown is kinda biggish when bundled, and on mobile, every KB counts to improve initial interaction.

**Comment by glortho** [comment]
Thanks for this @wmertens - I'll get a native modules build going here in the next couple days

**Comment by glortho** [comment]
this is now added as of 1.7.0. please let me know if this meets your expectations @wmertens
