### ISSUE TITLE
@keydown is error

### ISSUE THREAD

**Issue by phienngo** [glortho/react-keydown#48]
Hi admin,
I just add react-keydown, and using Class Decorator, but the error occur at character "@" ,
Please help me.

p/s: copy all source from demo: http://glortho.github.io/react-keydown/example/index.html
Thanks

**Comment by glortho** [comment]
Greetings @phienngo - you will need to transpile decorators with something like this https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy .

**Comment by phienngo** [comment]
Thanks so much @glortho
