### ISSUE TITLE
Documentation without decorators

### ISSUE THREAD

**Issue by EvHaus** [glortho/react-keydown#49]
All the documentation for `react-keydown` is using the legacy decorator feature of Babel. I'd like to move away from this Babel plugin but I can't figure out how to use `react-keydown` without decorators. Everything I've tried seems to fail.

Can you please add some simple documentation about how to wrap classes and class methods without using decorators?

**Comment by glortho** [comment]
@EvNaverniouk Sure, sorry about that. I removed that documentation a while back when it seemed no one was using this lib without decorators. In general I think it's probable (though not necessary) that you'll find other libs easier to use if you're not going to use the decorator pattern, at least for methods.

Class level decorators are still straightforward enough:

```
import keydown from 'react-keydown';

class MyClass extends React.Component {...}
export default keydown( 'ctrl+a' )( MyClass );
```

But method level decorators are not great:

```
import { setBinding } from 'react-keydown';

export default class MyClass extends React.Component {
  myMethod() {...}
}

setBinding(['ctrl+a'], MyClass.prototype.myMethod, MyClass.prototype);
```

**Comment by EvHaus** [comment]
Thank you for the quick response.

It is worthwhile promoting this to the README? Especially since `transform-decorators-legacy` will be going away in favor of `transform-decorators` which doesn't yet support method decorators.

**Comment by EvHaus** [comment]
Also, FYI, `import {setBinding} from 'react-keydown';` currently returns undefined. I had to use `import keydownStore from 'react-keydown/es/store'; console.log(keydownStore.setBinding);` to get it to work.
