### ISSUE TITLE
Multiple instances of same components seems to goof up

### ISSUE THREAD

**Issue by salmanm** [glortho/react-keydown#50]
I have a dropdown component which has the following

```
@keydown('esc')
  closeOnEscape (ev) {
    ev.preventDefault()
    this.close()
  }
```

and it seems that only the last one is ever called. Looks like its because of **same** handler passed to react-keydown and its only calling the last one.

Can anyone reproduce this issue?

**Comment by glortho** [comment]
@salmanm Is it possible this is what is happening?
>Duplicate keybindings for components that are mounted at the same time will not both fire. The more recently mounted component, or the one that has been focused or clicked most recently, will win. If you do want both to fire, decorate a common ancestor class with @keydown( ... ) and then use @keydownScoped( ... ) in the child components (or just inspect nextProps.keydown.event in both).

**Comment by salmanm** [comment]
Yep, sorry I missed that.
