### ISSUE TITLE
v1.7.3 broke support for simulated event testing

### ISSUE THREAD

**Issue by EvHaus** [glortho/react-keydown#53]
To test our components and their interactive with `react-keydown` we usually write tests which simulate events, like so:

```javascript
const event = document.createEvent('Event');
event.initEvent('keydown', true, true);
event.keyCode = 27;
event.which = 27;
document.dispatchEvent(event);
```

This then allows us to run tests to ensure `react-keydown` was bound correctly and fires the right callback.

However, after upgrading from `1.7.2` to `1.7.3` these tests are no longer working due to the changes in made here:

```javascript
function _shouldConsider(_ref3) {
  var ctrlKey = _ref3.ctrlKey,
      target = _ref3.target;

  return ctrlKey || !~['INPUT', 'SELECT', 'TEXTAREA'].indexOf(target.tagName) && target.getAttribute('role') !== 'textbox';
}
```

The issue is that this code assumes `target.getAttribute` is a valid function, however, in a test environment the target will be the `document` object which is created in `jsdom` and which may not actually have `getAttribute` defined.

Would it be possible to update `react-keydown` to check for the existence of this function first? So the code would become:

```javascript
return (
   ctrlKey ||
   !~['INPUT', 'SELECT', 'TEXTAREA'].indexOf(target.tagName) &&

   // Make sure the event target supports `getAttribute`
   target.getAttribute &&

   target.getAttribute('role') !== 'textbox'
);
```

Without this, we've had to revise our tests to do this in the meantime:

```javascript
const event = document.createEvent('Event');
event.initEvent('keydown', true, true);
event.keyCode = 27;
event.which = 27;
document.getAttribute = () => null; // Hacky Fix
document.dispatchEvent(event);
```

**Comment by glortho** [comment]
@EvNaverniouk try 1.7.4 and let me know if that fixes it for you

**Comment by EvHaus** [comment]
Wow, thanks for the super fast turnaround. That absolutely fixes the issue!
