### ISSUE TITLE
Watch modifiers keys

### ISSUE THREAD

**Issue by ImBrek** [glortho/react-keydown#54]
Hi, can I watch only ctrl click?

I tried this:
```
@keydown(17)
class Test extends Component{
}
```

But, if I am not wrong, `matchKeys` waits modifier + key

**Comment by glortho** [comment]
react-keydown isn't meant so much for clicks + modifiers. for your case I would just use regular click/mousedown event bindings and then inspect `event.ctrlKey` etc. but i'm certainly open to prs that add support for this in an elegant way.
