### ISSUE TITLE
Bound components lose focus when a click target is removed from the DOM

### ISSUE THREAD

**Issue by salmanm** [glortho/react-keydown#55]
The issue I have is similar to https://github.com/glortho/react-keydown/issues/16, but not sure.

When I decorate my class with `@keydown()` without any arguments, I get error as 

![image](https://user-images.githubusercontent.com/2510597/28537823-ce2f4f12-70c9-11e7-8393-64885e06ef19.png)

The reason I'm passing no args is that I want to capture all keys and I believe its decided [here](https://github.com/glortho/react-keydown/blob/master/src/store.js#L136).

Am I doing something wrong here? or its a compatibility bug like #16?

**Comment by glortho** [comment]
@salmanm we currently don't support triggering a function with all keys – we'll create an issue for that – but you can do something similar with the class decorator:
```jsx
@keydown
class MyComponent extends React.Component {
  componentWillReceiveProps({ keydown }) {
    if ( keydown && keydown.event ) this.method( keydown.event )
  }
}
```

**Comment by salmanm** [comment]
Great! Thanks for the quick response 😄

**Comment by salmanm** [comment]
But now I'm getting this error :(

![image](https://user-images.githubusercontent.com/2510597/28538959-a261d496-70cd-11e7-8f37-95e0d3b719a7.png)

I'm on v1.7.0

**Comment by glortho** [comment]
okay @salmanm can you paste in your code or pass me a repo link so i can try to reproduce?

also, what browser are you using?

**Comment by salmanm** [comment]
Alright I did some digging and found that it was due to `onMount` I was using from under the hood as suggested in https://github.com/glortho/react-keydown/issues/28#issuecomment-236898702.

I was facing some issues with focus so I had to use `onMount` to start capturing keys again after loosing focus from a child. I removed it and now this issue is resolved. However, I'm back to that focus issue again 😓

**Comment by glortho** [comment]
@salmanm it may be that you need to unbind that child component like so:
```jsx
import { onMount, onUnmount } from 'react-keydown/dist/event_handlers';

class MyChildComponent extends React.Component {

  componentWillReceiveProps( nextProps ) {
    if ( nextProps.isActive ) {
      onMount( this );
    } else {
      onUnmount( this );
    }
  }
  componentWillUnmount() {
    onUnmount( this );
  }
}
```
Does that help?

**Comment by salmanm** [comment]
I'm not using keydown in child component. So unbinding it there seems like an out of the place thing. It'd better if I can rebind parent/current component. But that I can't do because I have decorated class and the `instance` to be bound is not my class, it's the decorated class, which I
do not have access to. :(

**Comment by salmanm** [comment]
What works is creating an `activate` method in [decorator class](https://github.com/glortho/react-keydown/blob/master/src/decorators/class_decorator.js#L41) and passing as prop so that `this` decorated class can bind whenever required

```
activate() {
  onMount(this)
}

render() {
  return <WrappedComponent {...this.props} keydown={this.state} activate={this.activate} />;
}
```

But not sure if its a good idea

**Comment by salmanm** [comment]
So here's the problem
I had a dropdown child component. Which shows a div with a list of options and when you click on any option, it calls back `onSelect` prop function and closes the options. Now the `target` element from [here](https://github.com/glortho/react-keydown/blob/master/src/lib/dom_helpers.js#L56), is not even in the DOM, so this condition returned false and I loose focusable instance...

All I did is to hide dropdown in a `setTimeout` of 0, giving above condition a chance to detect which target the click happened.

Not sure if its the best.

**Comment by glortho** [comment]
@salmanm It does seem like we should expose a predictable hook for programmatic activation, along the lines of https://github.com/glortho/react-keydown/issues/55#issuecomment-317627321. There might be a danger of `activate` colliding with other props - can you think of another name that makes sense? Something like `takeKeydownEvents()`, `focusForKeydown()`,...?

**Comment by salmanm** [comment]
While adding such functionality is anyway a good idea and can be useful for many cases, but I still think using that in this case is a hacky solution. In ideal case, we should some how handle the case where we check clicked element.
```
if ( node && ( node === target || node.contains( target ) ) ) {
```
Here, if we can somehow manage to detect the target element before it gets removed from DOM, that'd be great.

Perhaps binding events in capture mode [here](https://github.com/glortho/react-keydown/blob/master/src/lib/listeners.js#L44) would help!

```
document.addEventListener( 'click', callback, true );
// first we get the event and then the element will be removed.
```

**Comment by glortho** [comment]
Hm well I'm not too experienced with capturing but I think since we have just the one listener on `document` we need to take advantage of bubbling. It seems to me that if `target` is no longer present [here](https://github.com/glortho/react-keydown/blob/master/src/event_handlers.js#L22) then all bets are off and we leave the store activation order as it is instead of going through this reshuffling. What do you think @salmanm ?

**Comment by salmanm** [comment]
Okay fair enough... So regarding your question on prop name, we could probably keep it `activateKeydown` or with an underscore `_activateKeydown` or whatever name you like.

We could alternatively pass the activate function in `context`, making all child components aware of it and be able to call it. But upto you what you prefer 😄

**Comment by glortho** [comment]
Okay thanks for the discussion @salmanm . I'll do a patch version with our fix for now and then work towards a minor version with the activation feature. Stay tuned.

**Comment by glortho** [comment]
Okay see if 1.7.5 fixed this issue for you @salmanm

**Comment by salmanm** [comment]
Sorry I couldn't check earlier

But you forgot to export `isAttached` function [here](https://github.com/glortho/react-keydown/commit/36206a716e41d89a5d8e1e191ccbf131b0dcd2b0#diff-47566d9141bbc57cf0c73f9a78d467c5R84) 

So 1.7.5 is broken completely.

**Comment by salmanm** [comment]
After some more research, turns out that logic in `isAttached` is not sufficient. Although it returns true, but the next step where we check `node.contains` returns false. I suggest we revert back to 1.7.4 and attempt a fix, test and then release 😄 

I can contribute if you like :)

**Comment by glortho** [comment]
@salmanm 1.7.5 and 1.7.6 were broken. 1.7.7 is what you need. Happy to review a pr for the rest!

**Comment by glortho** [comment]
btw also @salmanm it should be the case that `isAttached` returns false if your target node is in fact no longer in the DOM. are you not finding that to be the case? or maybe it just was failing because of broken builds. curious to hear if it works as of 1.7.7.

**Comment by salmanm** [comment]
I tried with 1.7.7 as well. In fact when I found 1.7.5 broken I fixed it locally and tried but none works.

Here's my finding:
you're checking for `node.parentNode` in `isAttached` function. Which obviously returns the `parentNode`. However, that `parentNode` itself is not present in DOM. Its my dropdown control. `target` element is `li` and its parent is `ul` which is in-turn wrapped in a `div` which is added to & removed from DOM as required.

So, if we modify `isAttached` to check for `document.body.contains(node)` then it returns correct result i.e. `false` in my case. This way your logic of **not** reshuffling `instance` order for non-existent elements works happily. 😄 

**BUT**, here's a bigger problem. This logic would definitely fail if I click on a _random_ element outside my focusable element. So if I have the same dropdown control _outside_ of the component decorated by `@keydown` then same logic would apply, no reshuffling for removed elements. This would be solved by another click on some other element. Works, but not ideal, right?

**Comment by salmanm** [comment]
I have opened https://github.com/glortho/react-keydown/pull/58 which implements my original suggestion from my previous https://github.com/glortho/react-keydown/issues/55#issuecomment-317741259.

I have tested and verified that it works fine.
