### ISSUE TITLE
1.9.0 breaking the lib

### ISSUE THREAD

**Issue by arcifius** [glortho/react-keydown#60]
1.9.0 isn't working here... It says keysArray is undefined

from: parseKeys(keysArray) function

**Comment by glortho** [comment]
Hm sorry to hear that. Show me your code and I'll see if I can reproduce @arcifius

**Comment by glortho** [comment]
Never mind I think I see the issue with class decorators that don't pass in any specific keys. Was that your set up? Anyway, try 1.9.1 and see if that fixes the issue for you @arcifius .

**Comment by stoplion** [comment]
Having same prob, using 1.9.1

**Comment by glortho** [comment]
Okay @stoplion could you post your error and a code snippet showing how you're using react-keydown?

**Comment by salmanm** [comment]
I've just tested both decorators, couldn't reproduce the case. In fact, I'm using it in my live app and works fine!

**Comment by glortho** [comment]
Okay thanks @salmanm - maybe he actually had 1.9.0. Closing until someone reproduces.

**Comment by salmanm** [comment]
@glortho btw, please could you release 1.9.2, my recent commits aren't yet on npm.

**Comment by glortho** [comment]
Done @salmanm . Thank you for that and for all your help around here!
