### ISSUE TITLE
Experimental Decorator Error

### ISSUE THREAD

**Issue by devarshi89** [glortho/react-keydown#62]
![image](https://user-images.githubusercontent.com/30517568/29169859-ca910904-7df3-11e7-879a-1a55e45f7f66.png)

I Tried With tsconfig.json But Not Working In Any Way. I Am Trying To Use @keydown('enter').

Please Help !

**Comment by glortho** [comment]
i'm not sure how typescript is transpiling decorators @devarshi89 . the method decorator in react-keydown expects transpilation according to this babel transform https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.

has anyone else tried in typescript? unless someone else has had success we may need to state in the README that typescript is not supported at this time.

though always happy to review a pr that adds support!

**Comment by salmanm** [comment]
This isn't a `react-keydown` issue.

Its the VSCode that shows this warning, and as far as I know, it would still be working with this warning.

Please check if you have the following in your `tsconfig.json` and also put the file under `./src` and not on root.

```
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

**Comment by devarshi89** [comment]
tsconfig.json In src
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "allowJs": true,
        "target": "ES6",
        "module": "amd",
        "sourceMap": true
    }
}

npm install babel-plugin-transform-decorators-legacy --save-dev

With The Help Of This Issue Resolved
