### ISSUE TITLE
sometime we end up with no events bound

### ISSUE THREAD

**Issue by salmanm** [glortho/react-keydown#66]
I have seen a similar issue as https://github.com/glortho/react-keydown/issues/64 last week which prevented all keydowns in a component.

Basically the problem is that we bind `keydown` event on `componentDidMount` and unbind it on `componentWillUnmount`, but due to incorrect sequence, this gets messed up and we end up with no bound events hence nothing works.

I could be wrong, but it looks like this happens because of the way React sequences `componentWillMount` & `componentWillUnmount`

> When replacing &lt;A /&gt; with &lt;B /&gt;, B.componentWillMount now always happens before A.componentWillUnmount. Previously, A.componentWillUnmount *could* fire first in some cases.

From https://github.com/facebook/react/issues/10294

**Comment by glortho** [comment]
interesting. see if 1.9.3 addresses this issue @salmanm . if not i'll take a closer look.

**Comment by glortho** [comment]
Are you still having this issue @salmanm ? I'm assuming not. Reopen if so.

**Comment by salmanm** [comment]
I got busy sorry. Yeah it's fine to close, I still haven't but I'll try it
soon.
