### ISSUE TITLE
Symbol is undefined in Internet Explorer

### ISSUE THREAD

**Issue by nperriwp** [glortho/react-keydown#67]
I was using version 1.7.7 of react-keydown and it worked fined in Internet Explorer. Once I updated to version 1.9.2 of react-keydown my project failed to work in Internet Explorer. Internet Explorer complains that Symbol is undefined. According to [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol), Symbol is not supported in Internet Explorer.

**Comment by salmanm** [comment]
@glortho We had usage of `Symbol` since before 1.7.7, wondering why then it has become a problem now!

**Comment by glortho** [comment]
@nperriwp @salmanm We would've been using Babel 5.x in <= 1.7.7 vs Babel 6.x in >= 1.9.2, so it must be that `Symbol` is now getting transpiled differently or not at all. Strange, however, that the poster in #64 is using IE but apparently not seeing the same issue. Maybe @lemonbutter was using Edge?

In any event, I'll look into our transpilation settings.

**Comment by salmanm** [comment]
I already checked, `Symbol` is not getting transpiled. It works with `babel-polyfill`, but then I wondered it works with Webpack which means that the consumer of this module would need to use it! Didn't sound right to me, and also I wasn't sure how to _not_ pollute global namespace if we want to use polyfill. 

I will wait for your findings :) @glortho

**Comment by glortho** [comment]
I've explicitly added the core-js symbol polyfill to our keys lib, where `Symbol` is being used. Please let us know if this works for you in 1.9.4 @nperriwp .

I assume others who are having success on IE probably just have Symbol polyfilled already somewhere in their stack.

**Comment by d-treegardener** [comment]
Our company uses IE11 in Edge mode for the project I'm working for. We use webpack for bundling.
Don't know if it's already polyfilled. We have a lot of dependencies 🙈

**Comment by glortho** [comment]
Okay thanks @lemonbutter that helps. We'll see what @nperriwp says from here.

**Comment by nperriwp** [comment]
Yes, 1.9.4 fixes the problem. Thank you.
