### ISSUE TITLE
how to 'preventDefault' ? 

### ISSUE THREAD

**Issue by LoeiFy** [glortho/react-keydown#73]
when use key 'up, down, left, right', the page will scroll by default. how to disable it ?

**Comment by glortho** [comment]
@LoeiFy are you using the method decorator? if so, it will receive `event` as its argument, which you should be able to use for `event.preventDefault()`:

```javascript
@keydown( 'up' )
goUp( event ) {
  event.preventDefault();
  ...
}
```

if you are using the component decorator, `keydown.event` will be passed down as a prop. in theory you can `keydown.event.preventDefault()` but i haven't tested that, and it's conceivable that there is a race condition preventing that from working properly.

Untested:
```javascript
@keydown( 'up' )
class MyComponent extends React.Component {
  componentWillReceiveProps({ keydown: keydownNext }) {
    const keydownThis = this.props.keydown;
    if ( keydownNext.event && !keydownThis.event ) {
      keydownNext.event.preventDefault();
    }
  }
}
```

**Comment by LoeiFy** [comment]
@glortho thanks
