### ISSUE TITLE
Support lambda/arrow functions

### ISSUE THREAD

**Issue by beeequeue** [glortho/react-keydown#82]
Decorator does not work if the property is a lambda function.

```jsx
export class Component extends React.PureComponent {
  constructor(props) {
    super(props)

    this.testOne = this.testOne.bind(this)
  }

  @keydown('enter')
  testOne() {
    console.log('one does run!')
  }

  @keydown('enter')
  testTwo = () => {
    console.log('two does not run!')
  }

  render() {
    return <div/>
  }
}
```

**Comment by glortho** [comment]
This must be some kind of collision between the babel legacy decorators transform, class properties, and our binding to `this`. However, methods decorated with `@keydown` already have the component instance bound to `this` so you should be fine using the standard method format.

For reference, from https://github.com/glortho/react-keydown#notes-disclaimers-and-tips:
> Since the only context we have for keydown events is the component, decorated methods receive the event as their sole argument and the component instance as context.
