### ISSUE TITLE
Can't use 'command' key

### ISSUE THREAD

**Issue by josemigallas** [glortho/react-keydown#86]
I am trying to implement a "save" shortcut for my react component, using `ctrl +s` and `cmd +s`. The former works as expected however it doesn't seem to recognize `CMD` although it is described in the docs.
```
@keydown("ctrl + s","cmd + s")
saveEvent(e) {
    e.prevendDefault();
    console.log("save");
}
```
I've tried using: `91 + 83`, `cmd + s`, `command + s` and `meta + s`. None of those worked.

Original code: https://github.com/aerogear/data-sync-ui/blob/master/ui/components/schema/SchemaContainer.js#L45

**Comment by glortho** [comment]
Sorry for the delay! The issue here will be that the browser `cmd + s` gets first priority. Does the save dialog pop up when you type `cmd + s`?

**Comment by josemigallas** [comment]
It does indeed @glortho

**Comment by salmanm** [comment]
@josemigallas It should work if you `preventDefault`

```
@keydown("ctrl + s","cmd + s")
saveEvent (e) {
    e.preventDefault()
    console.log("save");
}
```

**Comment by josemigallas** [comment]
~~Sorry for confusion @salmanm I already preventDefault in the original code [here](https://github.com/aerogear/data-sync-ui/blob/master/ui/components/schema/SchemaContainer.js#L45), I must've added after posting the issue. It doesn't fix the problem tho.~~
Ignore this! It's fixed, `e.preventDefault` was there however I forgot to commit the `cmd+s` bit.
Thanks @salmanm , @glortho it works as expected.
