### ISSUE TITLE
Combining keydown with onClick

### ISSUE THREAD

**Issue by Bobvantpadje** [glortho/react-keydown#89]
This is more of a question than an issue, but I wanted to know if it's possible to detect which keys are pressed within a function. I have a function which gets called onClick, but based on the keypresses it should work a little different (its a select functionality which should also work when pressing shift).

How would I, based on if the shift key is pressed, call a function to either just select one element or call another function to multi-select elements?

**Comment by glortho** [comment]
@Bobvantpadje you should be able to inspect the `event` argument that is passed to your decorated method to check the value of the `shiftKey` property.

**Comment by Bobvantpadje** [comment]
Thanks for the reply. I know that I can check for the `shiftKey` property. But I think the style with the decorators looks cleaner than writing an if-else statement in my function. I was wondering if it's possible to

**Comment by Bobvantpadje** [comment]
Thanks. I was just trying to see if the even has an shiftKey property. The problem that i'm facing now is that I get the click event and not the key event. My component structure looks something like this:

```
<WrapperComponent> 
    <ChildComponent/>
<WrapperComponent/>
```

The `ChildComponent` renders another type of component and this component has an onClick. But this component doesn't seem to detect my keypresses at all. My onClick looks like this:

```
@keydown('shift')
clickHandler(e) {
   doSomething();
}
```

But when I `console.log` the event it's just the click event and my `props` don't contain any keyPress even either.

**Comment by glortho** [comment]
Ah I see. Yes, the keydown event only fires when at least one the keys
pushed produces a character --
https://developer.mozilla.org/en-US/docs/Web/Events/keydown

**Comment by Bobvantpadje** [comment]
Ahh oke, thanks for your help!
